/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class BaixaEmprestimo extends javax.swing.JFrame {

//    String[] ModeloTabela = new String[]{"ID","Devolvido","Data de Devolução", "Prazo(dias)", "ID Livro", "ID Cliente"};
//    DefaultTableModel modelo = new DefaultTableModel(null,ModeloTabela);
    
    DefaultTableModel modelo = new DefaultTableModel(  
        new Object[] {"ID","Devolvido","Data de Devolução", "Prazo(dias)", "ID Livro", "ID Cliente"},0){
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false};    
            @Override  
            public boolean isCellEditable(int rowIndex, int columnIndex){  
                return canEdit [columnIndex];  
            }  
        };
        
    public BaixaEmprestimo() {
        initComponents();
        TabelaBaixa.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaBaixa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idLocBaixa = new javax.swing.JTextField();
        buscarID = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idCliBaixa1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Multa = new javax.swing.JTextField();
        diasUltrapassados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotaoFinalizar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        CalculaButton = new javax.swing.JButton();
        buscarTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TabelaBaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelaBaixa);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Baixa no Empréstimo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID do Cliente:");

        idLocBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLocBaixaActionPerformed(evt);
            }
        });

        buscarID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/busca_cliente2.png"))); // NOI18N
        buscarID.setText("Buscar ID");
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ID da Locação:");

        idCliBaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCliBaixa1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dias Ultrapassados:");

        Multa.setEditable(false);
        Multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultaActionPerformed(evt);
            }
        });

        diasUltrapassados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasUltrapassadosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Multa:");

        BotaoFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        BotaoFinalizar.setText("Finalizar");
        BotaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinalizarActionPerformed(evt);
            }
        });

        BotaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        CalculaButton.setText("Calcular Multa");
        CalculaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculaButtonActionPerformed(evt);
            }
        });

        buscarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/busca_cliente2.png"))); // NOI18N
        buscarTudo.setText("Todos os Empréstimos");
        buscarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalculaButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoFinalizar)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarID)
                        .addGap(18, 18, 18)
                        .addComponent(buscarTudo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idCliBaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Multa, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diasUltrapassados, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idLocBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idCliBaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarID)
                    .addComponent(buscarTudo))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLocBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diasUltrapassados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Multa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addComponent(CalculaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelar)
                    .addComponent(BotaoFinalizar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscaLocaNome(int busca, int tipo){
        Conexao c = new Conexao();
        if(busca > 0 ){
        try{
        ResultSet rs = c.BuscarClienteLocacao(busca, tipo);
        DefaultTableModel modelo = new DefaultTableModel(  
        new Object[] {"ID","Devolvido","Data de Devolução", "Prazo(dias)", "ID Livro", "ID Cliente"},0){
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false};    
            @Override  
            public boolean isCellEditable(int rowIndex, int columnIndex){  
                return canEdit [columnIndex];  
            }  
        };
        TabelaBaixa.setModel(modelo);
        while(rs.next()){
        modelo.addRow(new String[]{rs.getString("id_locacao"),
                rs.getString("devolvido"), rs.getString("data_devolucao"), rs.getString("prazo_devolucao"), 
                rs.getString("id_livro_FK"), rs.getString("id_cliente_FK")} );
        }
        
        }catch(SQLException e){JOptionPane.showMessageDialog(rootPane, "Erro na busca");}
        }else{
            JOptionPane.showMessageDialog(null,"Insira um ID válido");
        }
    }
    
    
    private void idCliBaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCliBaixa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCliBaixa1ActionPerformed

    private void buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDActionPerformed
        try {
        buscaLocaNome(Integer.parseInt(idCliBaixa1.getText()), 0);
        idCliBaixa1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Insira um ID válido!");
        }
    }//GEN-LAST:event_buscarIDActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        idLocBaixa.setText("");
        diasUltrapassados.setText("");
        Multa.setText("");
        
        dispose();
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void idLocBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLocBaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLocBaixaActionPerformed

    private void diasUltrapassadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasUltrapassadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasUltrapassadosActionPerformed

    private void MultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultaActionPerformed

    private void BotaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinalizarActionPerformed
        try{
            Conexao c = new Conexao();
            if(c.atualiza_locacao(Integer.parseInt(idLocBaixa.getText())) == true){
                JOptionPane.showMessageDialog(rootPane, "Baixa realizada com sucesso!");
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao dar baixa, tente corrigir os campos!");
            }
            idLocBaixa.setText("");
            diasUltrapassados.setText("");
            Multa.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Erro ao dar baixa, tente corrigir os campos!");
        } 
    }//GEN-LAST:event_BotaoFinalizarActionPerformed

    private void CalculaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculaButtonActionPerformed
        try {
            if(Integer.parseInt(diasUltrapassados.getText()) >= 0){    
                String multa = String.format("%.2f",(Integer.parseInt(diasUltrapassados.getText())) * (0.5));       
                Multa.setText("R$" + multa);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Insira um valor positivo!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Insira os dias corretamente!");
        }
        
    }//GEN-LAST:event_CalculaButtonActionPerformed

    private void buscarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTudoActionPerformed
        buscaLocaNome(1, 1);
        idCliBaixa1.setText("");
    }//GEN-LAST:event_buscarTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaixaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaixaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaixaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaixaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaixaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoFinalizar;
    private javax.swing.JButton CalculaButton;
    private javax.swing.JTextField Multa;
    private javax.swing.JTable TabelaBaixa;
    private javax.swing.JButton buscarID;
    private javax.swing.JButton buscarTudo;
    private javax.swing.JTextField diasUltrapassados;
    private javax.swing.JTextField idCliBaixa1;
    private javax.swing.JTextField idLocBaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
